/* Bundles the 2 Views PWA into a single deployable Cloudflare Worker script.
   Text files are JSON-packed and gzipped (decompressed in the Worker via
   DecompressionStream); PNGs ride along as base64. Output: worker.js
   Run: node tools/make-worker.js   (from the project root) */
'use strict';
const fs = require('fs');
const path = require('path');
const zlib = require('zlib');

const ROOT = path.join(__dirname, '..');
const CT = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.json': 'application/manifest+json',
  '.svg': 'image/svg+xml',
  '.txt': 'text/plain; charset=utf-8',
  '.xml': 'application/xml; charset=utf-8'
};
const TEXT_FILES = [
  'index.html', 'manifest.webmanifest', 'sw.js', 'css/style.css',
  'js/config.js', 'js/core/rng.js', 'js/core/events.js', 'js/core/storage.js',
  'js/core/audio.js', 'js/cosmetics/cosmetics.js', 'js/game/engine.js',
  'js/net/x-oauth.js', 'js/net/leaderboard.js', 'js/share/share.js',
  'js/ads/adslots.js', 'js/app.js', 'robots.txt', 'llms.txt', 'sitemap.xml'
];
const PNG_FILES = [
  'icons/icon-192.png', 'icons/icon-512.png', 'icons/icon-maskable-512.png',
  'icons/apple-touch-icon.png'
];

const files = {};
for (const rel of TEXT_FILES) {
  const body = fs.readFileSync(path.join(ROOT, rel), 'utf8');
  files['/' + rel] = {
    ct: CT[path.extname(rel)] || 'application/octet-stream',
    t: body,
    cc: rel === 'index.html' ? 'public, max-age=0, must-revalidate' : 'public, max-age=300'
  };
}
files['/icons/favicon.svg'] = { ct: 'image/svg+xml', t: fs.readFileSync(path.join(ROOT, 'icons/favicon.svg'), 'utf8'), cc: 'public, max-age=86400' };

const gz = zlib.gzipSync(Buffer.from(JSON.stringify(files)), { level: 9 }).toString('base64');

const pngs = {};
for (const rel of PNG_FILES) {
  pngs['/' + rel] = fs.readFileSync(path.join(ROOT, rel)).toString('base64');
}

const HANDLER = fs.readFileSync(path.join(__dirname, 'worker-handler.js'), 'utf8');

const chunkSize = 12000;
const chunks = [];
for (let i = 0; i < gz.length; i += chunkSize) { chunks.push(gz.slice(i, i + chunkSize)); }
const gzLines = chunks.map(c => '  "' + c + '"').join(',\n');

const worker = '/* 2 Views - auto-generated by tools/make-worker.js. Do not edit by hand. */\n' +
  'const GZ=[\n' + gzLines + '\n].join("");\n' +
  'const PNG=' + JSON.stringify(pngs) + ';\n' + HANDLER;

const out = path.join(__dirname, '..', '..', '..', '.openclaw', 'tmp');
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, '2views-worker.mjs'), worker);
console.log('worker.mjs written:', Buffer.byteLength(worker), 'bytes total,',
  chunks.length, 'GZ chunks, files:', Object.keys(files).length, 'text +', Object.keys(pngs).length, 'png');
